--[[
		init.lua
		Created: 08/06/2026 14:48:43
		Description: Autogenerated script file for the map desiccated_basin_cutscene.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local desiccated_basin_cutscene = {}

-------------------------------
-- Map Callbacks
-------------------------------
---desiccated_basin_cutscene.Init(map)
--Engine callback function
function desiccated_basin_cutscene.Init(map)


end

---desiccated_basin_cutscene.Enter(map)
--Engine callback function
function desiccated_basin_cutscene.Enter(map)
	
	desiccated_basin_cutscene.ClearCutscene(map)
	--[[
	if SV.ModData_EvolutionItemTrader.Boss_Encountered == false then
		desiccated_basin_cutscene.InitialCutscene(map)
	else
		if SV.ModData_EvolutionItemTrader.Boss_Defeated then
			desiccated_basin_cutscene.ClearCutscene(map)
		else
			desiccated_basin_cutscene.ReturnCutscene(map)
		end
	end
	]]--

end

---desiccated_basin_cutscene.Exit(map)
--Engine callback function
function desiccated_basin_cutscene.Exit(map)


end

---desiccated_basin_cutscene.Update(map)
--Engine callback function
function desiccated_basin_cutscene.Update(map)


end

---desiccated_basin_cutscene.GameSave(map)
--Engine callback function
function desiccated_basin_cutscene.GameSave(map)


end

---desiccated_basin_cutscene.GameLoad(map)
--Engine callback function
function desiccated_basin_cutscene.GameLoad(map)

	GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

-------------------------------
-- Cutscene Code
-------------------------------

function desiccated_basin_cutscene.SpawnPokemon(species, form, skin, gender, x, y, direction, instanceID, nameColor, name)
	local entityName = name
	if name == nil then
		entityName = _DATA:GetMonster(species).Name:ToLocal()
	end
	
	if instanceID == nil then
		instanceID = _DATA:GetMonster(species).Name:ToString()
	end
	if nameColor == nil then
		nameColor = "#00FFFF"
	end
	
	local monster = RogueEssence.Dungeon.MonsterID(species, form, skin, gender)
	chara = RogueEssence.Ground.GroundChar(monster, RogueElements.Loc(x, y), direction, "[color=" .. nameColor .. "]" .. entityName .. "[color]", instanceID)
	chara:ReloadEvents()
	GAME:GetCurrentGround():AddTempChar(chara)
	chara:OnMapInit()
	local result = RogueEssence.Script.TriggerResult()
	TASK:WaitTask(chara:RunEvent(RogueEssence.Script.LuaEngine.EEntLuaEventTypes.EntSpawned, result, chara))
	return chara
	
end

-- Cutscene when you first enter
function desiccated_basin_cutscene.InitialCutscene(map)
	
	-- Initialize cutscene
	GAME:CutsceneMode(true)
	
	GAME:MoveCamera(252, 200, 1, false)
	
	-- Set up characters
	local player = CH("PLAYER")
	local glaceon = desiccated_basin_cutscene.SpawnPokemon("glaceon", 0, "normal", Gender.Female, 244, 188, Direction.Up)
	
	-- Show map name and fade in
	UI:WaitShowTitle(GAME:GetCurrentGround().Name:ToLocal(), 20)
	GAME:WaitFrames(60)
	UI:WaitHideTitle(20)
	GAME:WaitFrames(30)
	GAME:FadeIn(20)
	
	local coro1 = TASK:BranchCoroutine(function() -- Player moves up
		GROUND:MoveToPosition(player, player.Position.X, player.Position.Y - 144, false, 0.75)
	end)
	local coro2 = TASK:BranchCoroutine(function() -- Glaceon turns and is surprised
		GAME:WaitFrames(120)
		GROUND:CharAnimateTurnTo(glaceon, Direction.Down, 4)
		GROUND:CharSetEmote(glaceon, "exclaim", 1)
		SOUND:PlayBattleSE("EVT_Emote_Shock_Bad")
		UI:SetSpeaker(glaceon)
		UI:SetSpeakerEmotion("Surprised")
		UI:WaitShowTimedDialogue("Waaah!![pause=60]", 10)
		UI:SetSpeakerEmotion("Angry")
		UI:WaitShowDialogue("I'm warning you![pause=30] Back off,[pause=10] or I'll freeze you solid!")
	end)
	local coro3 = TASK:BranchCoroutine(function() -- Glaceon backs away
		GAME:WaitFrames(210)
		GROUND:CharSetAnim(glaceon, "Walk", true)
		for i = 0, 16 do
			GROUND:TeleportTo(glaceon, glaceon.Position.X, glaceon.Position.Y - 1, Direction.Down)
			GAME:WaitFrames(4)
		end
		GROUND:CharEndAnim(glaceon)
	end)
	TASK:JoinCoroutines({coro1,coro2,coro3})
	GAME:WaitFrames(10)
	
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("Wait a minute...[pause=0] You're wearing...")
	GAME:WaitFrames(10)
	
	GROUND:CharSetEmote(glaceon, "notice", 1)
	SOUND:PlayBattleSE("EVT_Emote_Exclaim")
	GAME:WaitFrames(30)
	
	UI:SetSpeakerEmotion("Inspired")
	UI:WaitShowDialogue("Oh![pause=20] You're a rescue team leader![pause=0] Thank goodness!")
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("I had gone down here with [color=#00FFFF]Cacnea[color] to go find evolution items...")
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("But we got attacked by some strong-looking Pokémon and separated,[pause=10] and I had to run down here.")
	UI:SetSpeakerEmotion("Sad")
	UI:WaitShowDialogue("I was saving the Ice Stone I found for my brother,[pause=10] but I had to use it to fend them off...")
	GAME:WaitFrames(10)
	
	GROUND:MoveToPosition(glaceon, glaceon.Position.X, glaceon.Position.Y + 24, false, 0.5)
	GAME:WaitFrames(10)
	
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("We need to see if we can find [color=#00FFFF]Cacnea[color],[pause=10] too![pause=0] I'll come along with you.")
	GAME:WaitFrames(10)
	
	SOUND:PlayBGM("", true, 60)
	
	local coro1 = TASK:BranchCoroutine(function() -- Cacturne speaks
		UI:SetSpeaker(STRINGS:Format("\\uE040"))
		UI:WaitShowDialogue("Oh,[pause=10] don't worry.[pause=0] You're not going to have any trouble with that.")
		GAME:WaitFrames(10)
	end)
	local coro2 = TASK:BranchCoroutine(function() -- Glaceon turns and is surprised
		GAME:WaitFrames(10)
		GROUND:CharAnimateTurnTo(glaceon, Direction.Up, 4)
		GROUND:CharSetEmote(glaceon, "exclaim", 1)
		SOUND:PlayBattleSE("EVT_Emote_Exclaim_Surprised")
	end)
	TASK:JoinCoroutines({coro1,coro2})
	GAME:WaitFrames(10)
	
	UI:SetSpeaker(glaceon)
	UI:SetSpeakerEmotion("Stunned")
	UI:WaitShowDialogue("N-no...!")
	GAME:WaitFrames(10)
	
	local cacturne = desiccated_basin_cutscene.SpawnPokemon("cacturne", 0, "normal", Gender.Male, 0, 0, Direction.Down)
	GROUND:TeleportTo(cacturne, 244, 164, Direction.Down, 128)
	animId = RogueEssence.Content.GraphicsManager.GetAnimIndex("Hop")
	GAME:WaitFrames(20)
	
	for i = 1, 16 do
		GROUND:TeleportTo(cacturne, cacturne.Position.X, cacturne.Position.Y, Direction.Down, 128 - (i * 8))
		GROUND:CharSetAction(cacturne, RogueEssence.Ground.FrameGroundAction(cacturne.Position, cacturne.LocHeight, Direction.Down, animId, 1))
		GAME:WaitFrames(1)
	end
	GROUND:TeleportTo(cacturne, cacturne.Position.X, cacturne.Position.Y, Direction.Down, 0)
	animId = RogueEssence.Content.GraphicsManager.GetAnimIndex("Shoot")
	GROUND:CharSetAction(cacturne, RogueEssence.Ground.FrameGroundAction(cacturne.Position, cacturne.LocHeight, Direction.Down, animId, 1))
	GAME:WaitFrames(10)
	
	GROUND:CharSetAnim(cacturne, "SpAttack", false)
	GAME:WaitFrames(15)
	SOUND:PlayBattleSE("DUN_Payback_2")
	local coro1 = TASK:BranchCoroutine(function() -- Player moves
		GROUND:AnimateToPosition(player, "Hurt", Direction.Up, player.Position.X - 20, player.Position.Y + 12, 4, 2, 0)
	end)
	local coro2 = TASK:BranchCoroutine(function() -- Glaceon moves
		GROUND:AnimateToPosition(glaceon, "Hurt", Direction.Up, glaceon.Position.X + 20, glaceon.Position.Y + 37, 4, 2, 0)
	end)
	TASK:JoinCoroutines({coro1,coro2})
	GAME:WaitFrames(20)
	
	UI:SetSpeaker(cacturne)
	UI:WaitShowDialogue("Well, it looks like our prey can't run anymore.")
	UI:WaitShowDialogue("And not only that...")
	GAME:WaitFrames(10)
	
	local coro1 = TASK:BranchCoroutine(function() -- Camera moves down
		GAME:WaitFrames(20)
		GAME:MoveCamera(252, 248, 96, false)
	end)
	local coro2 = TASK:BranchCoroutine(function() -- Cacnea 1 comes in
		local cacnea = desiccated_basin_cutscene.SpawnPokemon("cacnea", 0, "normal", Gender.Male, 168, 336, Direction.Up, "Cacnea1")
		GROUND:MoveToPosition(cacnea, cacnea.Position.X - 16, cacnea.Position.Y - 120, false, 1)
		GAME:WaitFrames(10)
		GROUND:CharAnimateTurnTo(cacnea, Direction.Right, 4)
	end)
	local coro3 = TASK:BranchCoroutine(function() -- Cacnea 2 comes in
		GAME:WaitFrames(10)
		local cacnea = desiccated_basin_cutscene.SpawnPokemon("cacnea", 0, "normal", Gender.Male, 320, 336, Direction.Up, "Cacnea2")
		GROUND:MoveToPosition(cacnea, cacnea.Position.X + 16, cacnea.Position.Y - 120, false, 1)
		GAME:WaitFrames(10)
		GROUND:CharAnimateTurnTo(cacnea, Direction.Left, 4)
	end)
	local coro4 = TASK:BranchCoroutine(function() -- Cacnea 3 comes in
		GAME:WaitFrames(50)
		local cacnea = desiccated_basin_cutscene.SpawnPokemon("cacnea", 0, "normal", Gender.Male, 168, 384, Direction.Up, "Cacnea3")
		GROUND:MoveToPosition(cacnea, cacnea.Position.X, cacnea.Position.Y - 96, false, 1)
		GAME:WaitFrames(10)
		GROUND:CharAnimateTurnTo(cacnea, Direction.UpRight, 4)
	end)
	local coro5 = TASK:BranchCoroutine(function() -- Cacnea 4 comes in
		GAME:WaitFrames(70)
		local cacnea = desiccated_basin_cutscene.SpawnPokemon("cacnea", 0, "normal", Gender.Male, 320, 384, Direction.Up, "Cacnea4")
		GROUND:MoveToPosition(cacnea, cacnea.Position.X, cacnea.Position.Y - 96, false, 1)
		GAME:WaitFrames(10)
		GROUND:CharAnimateTurnTo(cacnea, Direction.UpLeft, 4)
	end)
	local coro6 = TASK:BranchCoroutine(function() -- Player turns to see
		GROUND:CharAnimateTurnTo(player, Direction.DownLeft, 4)
		GAME:WaitFrames(40)
		GROUND:CharAnimateTurnTo(player, Direction.Up, 4)
	end)
	local coro7 = TASK:BranchCoroutine(function() -- Glaceon turns to see
		GAME:WaitFrames(20)
		GROUND:CharAnimateTurnTo(glaceon, Direction.DownRight, 4)
		GAME:WaitFrames(50)
		GROUND:CharAnimateTurnTo(glaceon, Direction.Up, 4)
	end)
	TASK:JoinCoroutines({coro1,coro2,coro3,coro4,coro5,coro6,coro7})
	GAME:WaitFrames(10)
	
	UI:SetSpeaker(cacturne)
	UI:WaitShowDialogue("But it's baited an exploration team in as well.")
	GAME:WaitFrames(20)
	
	UI:SetSpeaker(glaceon)
	UI:SetSpeakerEmotion("Determined")
	UI:WaitShowDialogue("You...[pause=0] You think I'm afraid,[pause=10] don't you?!")
	UI:SetSpeakerEmotion("Angry")
	UI:WaitShowTimedDialogue("Well, you're all Grass-type Pokémon![pause=0] So if you don't back off,[pause=10] I'll-", 20)
	GAME:WaitFrames(10)
	
	-- Tyranitar drops in
	-- Target pos is 264, 216
	
	local tyranitar = desiccated_basin_cutscene.SpawnPokemon("tyranitar", 0, "normal", Gender.Male, 264, 200, Direction.Down)
	GROUND:TeleportTo(tyranitar, 264, 200, Direction.Down, 128)
	animId = RogueEssence.Content.GraphicsManager.GetAnimIndex("Strike")
	SOUND:PlayBattleSE("_UNK_DUN_Throw_Card")
	GAME:WaitFrames(10)
	
	for i = 1, 16 do
		GROUND:TeleportTo(tyranitar, tyranitar.Position.X, tyranitar.Position.Y + 1, Direction.Down, 128 - (i * 8))
		GROUND:CharSetAction(tyranitar, RogueEssence.Ground.FrameGroundAction(tyranitar.Position, tyranitar.LocHeight, Direction.Down, animId, 0))
		GAME:WaitFrames(1)
	end
	SOUND:PlayBattleSE("DUN_Rock_Smash")
	GROUND:EntTurn(player, Direction.UpRight)
	GROUND:CharSetAnim(tyranitar, "Strike", false)
	GAME:WaitFrames(12)
	SOUND:PlayBattleSE("EVT_Tackle")
	GROUND:EntTurn(glaceon, Direction.Right)
	GROUND:CharSetAnim(glaceon, "Pain", false)
	animId = RogueEssence.Content.GraphicsManager.GetAnimIndex("Trip")
	
	local coro1 = TASK:BranchCoroutine(function() -- Glaceon moves and falls
		for i = 1, 4 do
			GROUND:TeleportTo(glaceon, glaceon.Position.X, glaceon.Position.Y + 2, Direction.Right, 0)
			GAME:WaitFrames(1)
		end
		for i = 1, 16 do
			GROUND:TeleportTo(glaceon, glaceon.Position.X, glaceon.Position.Y + 1, Direction.Right, 0)
			GAME:WaitFrames(1)
		end
		
		SOUND:PlayBattleSE("EVT_CH03_Boss_Collapse")
		for i = 0, 4 do
			GROUND:CharSetAction(glaceon, RogueEssence.Ground.FrameGroundAction(glaceon.Position, glaceon.LocHeight, Direction.Right, animId, i))
			GAME:WaitFrames(5)
		end
	end)
	local coro2 = TASK:BranchCoroutine(function() -- Glaceon screams
		UI:SetSpeaker(glaceon)
		UI:SetSpeakerEmotion("Shouting")
		UI:WaitShowDialogue("Uwaaaahhhhh!!![pause=90]")
	end)
	local coro3 = TASK:BranchCoroutine(function() -- Player is surprised, then goes over to Glaceon
		GROUND:EntTurn(player, Direction.UpRight)
		GROUND:CharSetEmote(player, "exclaim", 1)
		GAME:WaitFrames(35)
		GROUND:CharAnimateTurnTo(player, Direction.DownRight, 3)
		GROUND:MoveToPosition(player, player.Position.X + 20, player.Position.Y + 26, false, 1.5)
		GAME:WaitFrames(5)
		GROUND:EntTurn(player, Direction.Right)
		GAME:WaitFrames(40)
		GROUND:CharAnimateTurnTo(player, Direction.Up, 4)
	end)
	TASK:JoinCoroutines({coro1,coro2,coro3})
	GAME:WaitFrames(10)
	
	UI:SetSpeaker(cacturne)
	UI:WaitShowDialogue("You will speak when spoken to by the ruler of the Desert Clan.")
	GAME:WaitFrames(10)
	
	local coro1 = TASK:BranchCoroutine(function() -- Drapion appears
		local drapion = desiccated_basin_cutscene.SpawnPokemon("drapion", 0, "normal", Gender.Female, 196, 180, Direction.Down)
		GROUND:TeleportTo(drapion, drapion.Position.X, drapion.Position.Y, Direction.Down, 120)
		GAME:WaitFrames(10)
		SOUND:PlayBattleSE("_UNK_DUN_Throw_Card")
		for i = 1, 20 do
			GROUND:TeleportTo(drapion, drapion.Position.X, drapion.Position.Y, Direction.Down, 120 - (i * 6))
			GAME:WaitFrames(1)
		end
		SOUND:PlayBattleSE("DUN_Rock_Smash")
	end)
	local coro2 = TASK:BranchCoroutine(function() -- Excadrill appears
		local excadrill = desiccated_basin_cutscene.SpawnPokemon("excadrill", 0, "normal", Gender.Male, 272, 336, Direction.Up)
		GROUND:TeleportTo(excadrill, excadrill.Position.X, excadrill.Position.Y, Direction.Up, 240)
		GAME:WaitFrames(30)
		SOUND:PlayBattleSE("_UNK_DUN_Throw_Card")
		for i = 1, 40 do
			GROUND:TeleportTo(excadrill, excadrill.Position.X, excadrill.Position.Y, Direction.Up, 240 - (i * 6))
			GAME:WaitFrames(1)
		end
		SOUND:PlayBattleSE("DUN_Rock_Smash")
	end)
	local coro3 = TASK:BranchCoroutine(function() -- Golem appears
		local golem = desiccated_basin_cutscene.SpawnPokemon("golem", 0, "normal", Gender.Male, 216, 336, Direction.Up)
		GROUND:TeleportTo(golem, golem.Position.X, golem.Position.Y, Direction.Up, 240)
		GAME:WaitFrames(60)
		SOUND:PlayBattleSE("_UNK_DUN_Throw_Card")
		for i = 1, 20 do
			GROUND:TeleportTo(golem, golem.Position.X, golem.Position.Y, Direction.Up, 240 - (i * 12))
			GAME:WaitFrames(1)
		end
		SOUND:PlayBattleSE("DUN_Rock_Climb_2")
	end)
	local coro4 = TASK:BranchCoroutine(function() -- Tyranitar returns to Cacturne's side
		GROUND:CharAnimateTurnTo(tyranitar, Direction.UpRight, 6)
		GAME:WaitFrames(10)
		GROUND:MoveToPosition(tyranitar, 292, 180, false, 0.5)
		GAME:WaitFrames(10)
		GROUND:CharAnimateTurnTo(tyranitar, Direction.Down, 6)
	end)
	TASK:JoinCoroutines({coro1,coro2,coro3,coro4})
	GAME:WaitFrames(20)
	
	UI:SetSpeaker(cacturne)
	UI:WaitShowDialogue("[color=#00FFFF]Honchkrow[color] and [color=#00FFFF]Salamence[color] may control the trades in other items...")
	UI:WaitShowDialogue("But I,[pause=10] the true heir to the old guildmaster,[pause=10] have the supply of evolution items in my grip.")
	GAME:WaitFrames(10)
	
	animId = RogueEssence.Content.GraphicsManager.GetAnimIndex("HitGround")
	GROUND:CharSetAction(glaceon, RogueEssence.Ground.FrameGroundAction(glaceon.Position, glaceon.LocHeight, Direction.Right, animId, 6))
	
	UI:SetSpeaker(glaceon)
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue("Ooft...!")
	GAME:WaitFrames(30)
	
	GROUND:CharSetAction(glaceon, RogueEssence.Ground.FrameGroundAction(glaceon.Position, glaceon.LocHeight, Direction.Right, animId, 7))
	GAME:WaitFrames(20)
	GROUND:CharSetAnim(glaceon, "None", true)
	GAME:WaitFrames(40)
	GROUND:CharAnimateTurnTo(glaceon, Direction.Up, 4)
	GAME:WaitFrames(10)
	
	UI:SetSpeaker(glaceon)
	UI:SetSpeakerEmotion("Angry")
	UI:WaitShowDialogue("What do you WANT,[pause=10] anyway?!")
	UI:WaitShowDialogue("Me and my brother just wanted to evolve![pause=0] What's wrong with that?!")
	GAME:WaitFrames(10)
	
	UI:SetSpeaker(cacturne)
	UI:WaitShowDialogue("We're just defending our interests.")
	UI:WaitShowDialogue("If you'd bought from a [color=#00FFFF]Kecleon[color] or [color=#00FFFF]Shuckle[color] shop,[pause=10] we'd have no quarrel.")
	UI:WaitShowDialogue("But you illegally distributed evolution items without our oversight.[pause=0] And we can't have that,[pause=10] can we?")
	GAME:WaitFrames(10)
	
	-- Minions get closer and boss music starts
	SOUND:PlayBGM("Boss Battle 2.ogg", true)
	
	local coro1 = TASK:BranchCoroutine(function() -- Drapion gets closer
		GAME:WaitFrames(20)
		local drapion = CH("Drapion")
		GROUND:MoveToPosition(drapion, drapion.Position.X + 4, drapion.Position.Y + 8, false, 0.25)
	end)
	local coro2 = TASK:BranchCoroutine(function() -- Tyranitar gets closer
		GAME:WaitFrames(30)
		local tyranitar = CH("Tyranitar")
		GROUND:MoveToPosition(tyranitar, tyranitar.Position.X - 4, tyranitar.Position.Y + 8, false, 0.25)
	end)
	local coro3 = TASK:BranchCoroutine(function() -- Excadrill gets closer
		GAME:WaitFrames(10)
		local excadrill = CH("Excadrill")
		GROUND:MoveToPosition(excadrill, excadrill.Position.X - 4, excadrill.Position.Y - 8, false, 0.25)
	end)
	local coro4 = TASK:BranchCoroutine(function() -- Golem gets closer
		GAME:WaitFrames(55)
		local golem = CH("Golem")
		GROUND:MoveToPosition(golem, golem.Position.X + 4, golem.Position.Y - 8, false, 0.25)
	end)
	local coro5 = TASK:BranchCoroutine(function() -- Cacnea1 gets closer
		GAME:WaitFrames(15)
		local cacnea = CH("Cacnea1")
		GROUND:MoveToPosition(cacnea, cacnea.Position.X + 8, cacnea.Position.Y + 4, false, 0.25)
	end)
	local coro6 = TASK:BranchCoroutine(function() -- Cacnea2 gets closer
		GAME:WaitFrames(70)
		local cacnea = CH("Cacnea2")
		GROUND:MoveToPosition(cacnea, cacnea.Position.X - 8, cacnea.Position.Y + 4, false, 0.25)
	end)
	local coro7 = TASK:BranchCoroutine(function() -- Cacnea3 gets closer
		GAME:WaitFrames(35)
		local cacnea = CH("Cacnea3")
		GROUND:MoveToPosition(cacnea, cacnea.Position.X + 6, cacnea.Position.Y - 6, false, 0.25)
	end)
	local coro8 = TASK:BranchCoroutine(function() -- Cacnea4 gets closer
		GAME:WaitFrames(45)
		local cacnea = CH("Cacnea4")
		GROUND:MoveToPosition(cacnea, cacnea.Position.X - 6, cacnea.Position.Y - 6, false, 0.25)
	end)
	TASK:JoinCoroutines({coro1,coro2,coro3,coro4,coro5,coro6,coro7,coro8})
	GAME:WaitFrames(10)
	
	UI:SetSpeaker(cacturne)
	UI:WaitShowDialogue("The punishment for defying our business rules is to be barred from ever trading in evolution items again...")
	GAME:WaitFrames(10)
	
	-- Screen flashes
	SOUND:PlayBattleSE("EVT_Battle_Flash")
	GAME:FadeOut(true, 4)
	GAME:FadeIn(4)
	GAME:WaitFrames(10)
	
	UI:SetSpeaker(cacturne)
	UI:SetSpeakerEmotion("Special0")
	UI:WaitShowDialogue("Under penalty of death.")
	GAME:WaitFrames(10)
	
	-- Add Glaceon to the player's party
	local mon_id = RogueEssence.Dungeon.MonsterID("glaceon", 0, "normal", Gender.Female)
	local glaceon = _DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, mon_id, 35, "snow_cloak", 0)
	glaceon.Discriminator = _DATA.Save.Rand:Next()
	local talk_evt = RogueEssence.Dungeon.BattleScriptEvent("AllyInteract")
	glaceon.ActionEvents:Add(talk_evt)
	
	glaceon.Level = 35
	glaceon.IsPartner = false
	glaceon.MaxHPBonus = 20
	glaceon.AtkBonus = 20
	glaceon.DefBonus = 20
	glaceon.MAtkBonus = 20
	glaceon.MDefBonus = 20
	glaceon.SpeedBonus = 20
	
	glaceon:ReplaceSkill("icy_wind", 0, true)
	glaceon:ReplaceSkill("helping_hand", 1, true)
	glaceon:ReplaceSkill("barrier", 2, true)
	glaceon:ReplaceSkill("sand_attack", 3, false)
	
	GAME:AddPlayerGuest(glaceon)
	glaceon:FullRestore()
	glaceon:RefreshTraits()
	
	-- Set boss as encountered
	if SV.ModData_EvolutionItemTrader ~= nil then
		SV.ModData_EvolutionItemTrader.Boss_Encountered = true
	end
  
	-- Boss battle begins
	COMMON.BossTransition(true)

	GAME:CutsceneMode(false)

	GAME:ContinueDungeon('depleted_basin', 6, 0, 0)
	

end

-- Cutscene for if you lose and return
function desiccated_basin_cutscene.ReturnCutscene(map)
	
	-- Initialize cutscene
	GAME:CutsceneMode(true)
	
	SOUND:PlayBGM("", false)
	
	GAME:MoveCamera(252, 248, 1, false)
	
	-- Set up characters
	local player = CH("PLAYER")
	GROUND:TeleportTo(player, player.Position.X, 254, Direction.Up)
	local glaceon = desiccated_basin_cutscene.SpawnPokemon("glaceon", 0, "normal", Gender.Female, 260, 252, Direction.Up)
	
	local cacturne = desiccated_basin_cutscene.SpawnPokemon("cacturne", 0, "normal", Gender.Male, 244, 164, Direction.Down)
	
	local drapion = desiccated_basin_cutscene.SpawnPokemon("drapion", 0, "normal", Gender.Female, 196, 180, Direction.Down)
	local tyranitar = desiccated_basin_cutscene.SpawnPokemon("tyranitar", 0, "normal", Gender.Male, 292, 180, Direction.Down)
	local excadrill = desiccated_basin_cutscene.SpawnPokemon("excadrill", 0, "normal", Gender.Male, 272, 336, Direction.Up)
	local golem = desiccated_basin_cutscene.SpawnPokemon("golem", 0, "normal", Gender.Male, 216, 336, Direction.Up)
	
	local cacnea1 = desiccated_basin_cutscene.SpawnPokemon("cacnea", 0, "normal", Gender.Male, 152, 216, Direction.Right, "Cacnea1")
	local cacnea2 = desiccated_basin_cutscene.SpawnPokemon("cacnea", 0, "normal", Gender.Male, 336, 216, Direction.Left, "Cacnea2")
	local cacnea3 = desiccated_basin_cutscene.SpawnPokemon("cacnea", 0, "normal", Gender.Male, 168, 288, Direction.UpRight, "Cacnea3")
	local cacnea4 = desiccated_basin_cutscene.SpawnPokemon("cacnea", 0, "normal", Gender.Male, 320, 288, Direction.UpLeft, "Cacnea4")
	
	-- Show map name and fade in
	UI:WaitShowTitle(GAME:GetCurrentGround().Name:ToLocal(), 20)
	GAME:WaitFrames(60)
	UI:WaitHideTitle(20)
	GAME:WaitFrames(30)
	GAME:FadeIn(20)
	GAME:WaitFrames(30)
	
	-- Minions get closer and boss music starts
	SOUND:PlayBGM("Boss Battle 2.ogg", true)
	
	local coro1 = TASK:BranchCoroutine(function() -- Drapion gets closer
		GAME:WaitFrames(20)
		local drapion = CH("Drapion")
		GROUND:MoveToPosition(drapion, drapion.Position.X + 4, drapion.Position.Y + 8, false, 0.25)
	end)
	local coro2 = TASK:BranchCoroutine(function() -- Tyranitar gets closer
		GAME:WaitFrames(30)
		local tyranitar = CH("Tyranitar")
		GROUND:MoveToPosition(tyranitar, tyranitar.Position.X - 4, tyranitar.Position.Y + 8, false, 0.25)
	end)
	local coro3 = TASK:BranchCoroutine(function() -- Excadrill gets closer
		GAME:WaitFrames(10)
		local excadrill = CH("Excadrill")
		GROUND:MoveToPosition(excadrill, excadrill.Position.X - 4, excadrill.Position.Y - 8, false, 0.25)
	end)
	local coro4 = TASK:BranchCoroutine(function() -- Golem gets closer
		GAME:WaitFrames(55)
		local golem = CH("Golem")
		GROUND:MoveToPosition(golem, golem.Position.X + 4, golem.Position.Y - 8, false, 0.25)
	end)
	local coro5 = TASK:BranchCoroutine(function() -- Cacnea1 gets closer
		GAME:WaitFrames(15)
		local cacnea = CH("Cacnea1")
		GROUND:MoveToPosition(cacnea, cacnea.Position.X + 8, cacnea.Position.Y + 4, false, 0.25)
	end)
	local coro6 = TASK:BranchCoroutine(function() -- Cacnea2 gets closer
		GAME:WaitFrames(70)
		local cacnea = CH("Cacnea2")
		GROUND:MoveToPosition(cacnea, cacnea.Position.X - 8, cacnea.Position.Y + 4, false, 0.25)
	end)
	local coro7 = TASK:BranchCoroutine(function() -- Cacnea3 gets closer
		GAME:WaitFrames(35)
		local cacnea = CH("Cacnea3")
		GROUND:MoveToPosition(cacnea, cacnea.Position.X + 6, cacnea.Position.Y - 6, false, 0.25)
	end)
	local coro8 = TASK:BranchCoroutine(function() -- Cacnea4 gets closer
		GAME:WaitFrames(45)
		local cacnea = CH("Cacnea4")
		GROUND:MoveToPosition(cacnea, cacnea.Position.X - 6, cacnea.Position.Y - 6, false, 0.25)
	end)
	TASK:JoinCoroutines({coro1,coro2,coro3,coro4,coro5,coro6,coro7,coro8})
	GAME:WaitFrames(10)
	
	UI:SetSpeaker(cacturne)
	UI:WaitShowDialogue("The punishment for defying our business rules is to be barred from ever trading in evolution items again...")
	GAME:WaitFrames(10)
	
	-- Screen flashes
	SOUND:PlayBattleSE("EVT_Battle_Flash")
	GAME:FadeOut(true, 4)
	GAME:FadeIn(4)
	GAME:WaitFrames(10)
	
	UI:SetSpeaker(cacturne)
	UI:SetSpeakerEmotion("Special0")
	UI:WaitShowDialogue("Under penalty of death.")
	GAME:WaitFrames(10)
	
	-- Add Glaceon to the player's party
	local mon_id = RogueEssence.Dungeon.MonsterID("glaceon", 0, "normal", Gender.Female)
	local glaceon = _DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, mon_id, 35, "snow_cloak", 0)
	glaceon.Discriminator = _DATA.Save.Rand:Next()
	local talk_evt = RogueEssence.Dungeon.BattleScriptEvent("AllyInteract")
	glaceon.ActionEvents:Add(talk_evt)
	
	glaceon.Level = 35
	glaceon.IsPartner = false
	glaceon.MaxHPBonus = 20
	glaceon.AtkBonus = 20
	glaceon.DefBonus = 20
	glaceon.MAtkBonus = 20
	glaceon.MDefBonus = 20
	glaceon.SpeedBonus = 20
	
	glaceon:ReplaceSkill("icy_wind", 0, true)
	glaceon:ReplaceSkill("helping_hand", 1, true)
	glaceon:ReplaceSkill("barrier", 2, true)
	glaceon:ReplaceSkill("sand_attack", 3, false)
	
	GAME:AddPlayerGuest(glaceon)
	glaceon:FullRestore()
	glaceon:RefreshTraits()
	
	-- Set boss as encountered
	if SV.ModData_EvolutionItemTrader ~= nil then
		SV.ModData_EvolutionItemTrader.Boss_Encountered = true
	end
  
	-- Boss battle begins
	COMMON.BossTransition(true)

	GAME:CutsceneMode(false)

	GAME:ContinueDungeon('depleted_basin', 6, 0, 0)
	
end

-- Post-boss victory cutscene
function desiccated_basin_cutscene.ClearCutscene(map)
	
	-- Initialize cutscene
	GAME:CutsceneMode(true)
	
	SOUND:PlayBGM("", false)
	
	GAME:MoveCamera(252, 248, 1, false)
	
	-- Set up characters
	local player = CH("PLAYER")
	GROUND:TeleportTo(player, 232, 254, Direction.Left)
	local glaceon = desiccated_basin_cutscene.SpawnPokemon("glaceon", 0, "normal", Gender.Female, 256, 252, Direction.Right)
	
	local cacturne = desiccated_basin_cutscene.SpawnPokemon("cacturne", 0, "normal", Gender.Male, 244, 164, Direction.Down)
	
	local drapion = desiccated_basin_cutscene.SpawnPokemon("drapion", 0, "normal", Gender.Female, 196, 180, Direction.Down)
	local tyranitar = desiccated_basin_cutscene.SpawnPokemon("tyranitar", 0, "normal", Gender.Male, 292, 180, Direction.Down)
	local excadrill = desiccated_basin_cutscene.SpawnPokemon("excadrill", 0, "normal", Gender.Male, 272, 336, Direction.Up)
	local golem = desiccated_basin_cutscene.SpawnPokemon("golem", 0, "normal", Gender.Male, 216, 336, Direction.Up)
	
	local cacnea1 = desiccated_basin_cutscene.SpawnPokemon("cacnea", 0, "normal", Gender.Male, 152, 216, Direction.Right, "Cacnea1")
	local cacnea2 = desiccated_basin_cutscene.SpawnPokemon("cacnea", 0, "normal", Gender.Male, 336, 216, Direction.Left, "Cacnea2")
	local cacnea3 = desiccated_basin_cutscene.SpawnPokemon("cacnea", 0, "normal", Gender.Male, 168, 288, Direction.UpRight, "Cacnea3")
	local cacnea4 = desiccated_basin_cutscene.SpawnPokemon("cacnea", 0, "normal", Gender.Male, 320, 288, Direction.UpLeft, "Cacnea4")
	
	local coro1 = TASK:BranchCoroutine(function() -- Cacturne is knocked back
		local moving_char = cacturne
		GROUND:TeleportTo(moving_char, moving_char.Position.X, moving_char.Position.Y + 48, Direction.Down)
		GAME:WaitFrames(10)
		GROUND:AnimateToPosition(moving_char, "Hurt", Direction.Down, moving_char.Position.X, moving_char.Position.Y - 12, 4, 2, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", Direction.Down, moving_char.Position.X, moving_char.Position.Y - 12, 4, 1.5, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", Direction.Down, moving_char.Position.X, moving_char.Position.Y - 12, 4, 1, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", Direction.Down, moving_char.Position.X, moving_char.Position.Y - 12, 4, 0.5, 0)
		GROUND:CharSetAnim(moving_char, "Hurt", true)
		GAME:WaitFrames(20)
		GROUND:CharSetAnim(moving_char, "None", true)
	end)
	local coro2 = TASK:BranchCoroutine(function() -- Drapion is knocked back
		local moving_char = drapion
		GROUND:TeleportTo(moving_char, moving_char.Position.X + 12, moving_char.Position.Y + 46, Direction.DownRight)
		GAME:WaitFrames(10)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X - 3, moving_char.Position.Y - 12, 4, 2, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X - 3, moving_char.Position.Y - 12, 4, 1.5, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X - 3, moving_char.Position.Y - 11, 4, 1, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X - 3, moving_char.Position.Y - 11, 4, 0.5, 0)
		GROUND:CharSetAnim(moving_char, "Hurt", true)
		GAME:WaitFrames(20)
		GROUND:CharSetAnim(moving_char, "None", true)
	end)
	local coro3 = TASK:BranchCoroutine(function() -- Tyranitar is knocked back
		local moving_char = tyranitar
		GROUND:TeleportTo(moving_char, moving_char.Position.X - 12, moving_char.Position.Y + 46, Direction.DownLeft)
		GAME:WaitFrames(10)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X + 3, moving_char.Position.Y - 12, 4, 2, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X + 3, moving_char.Position.Y - 12, 4, 1.5, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X + 3, moving_char.Position.Y - 11, 4, 1, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X + 3, moving_char.Position.Y - 11, 4, 0.5, 0)
		GROUND:CharSetAnim(moving_char, "Hurt", true)
		GAME:WaitFrames(20)
		GROUND:CharSetAnim(moving_char, "None", true)
	end)
	local coro4 = TASK:BranchCoroutine(function() -- Golem is knocked back
		local moving_char = golem
		GROUND:TeleportTo(moving_char, moving_char.Position.X + 12, moving_char.Position.Y - 46, Direction.Up)
		GAME:WaitFrames(10)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X - 3, moving_char.Position.Y + 12, 4, 2, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X - 3, moving_char.Position.Y + 12, 4, 1.5, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X - 3, moving_char.Position.Y + 11, 4, 1, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X - 3, moving_char.Position.Y + 11, 4, 0.5, 0)
		GROUND:CharSetAnim(moving_char, "Hurt", true)
		GAME:WaitFrames(20)
		GROUND:CharSetAnim(moving_char, "None", true)
	end)
	local coro5 = TASK:BranchCoroutine(function() -- Excadrill is knocked back
		local moving_char = excadrill
		GROUND:TeleportTo(moving_char, moving_char.Position.X - 12, moving_char.Position.Y - 46, Direction.Up)
		GAME:WaitFrames(10)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X + 3, moving_char.Position.Y + 12, 4, 2, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X + 3, moving_char.Position.Y + 12, 4, 1.5, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X + 3, moving_char.Position.Y + 11, 4, 1, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X + 3, moving_char.Position.Y + 11, 4, 0.5, 0)
		GROUND:CharSetAnim(moving_char, "Hurt", true)
		GAME:WaitFrames(20)
		GROUND:CharSetAnim(moving_char, "None", true)
	end)
	
	local coro6 = TASK:BranchCoroutine(function() -- Cacnea1 is knocked back
		local moving_char = cacnea1
		GROUND:TeleportTo(moving_char, moving_char.Position.X + 48, moving_char.Position.Y + 24, Direction.Right)
		GAME:WaitFrames(10)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X - 12, moving_char.Position.Y - 6, 4, 2, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X - 12, moving_char.Position.Y - 6, 4, 1.5, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X - 12, moving_char.Position.Y - 6, 4, 1, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X - 12, moving_char.Position.Y - 6, 4, 0.5, 0)
		GROUND:CharSetAnim(moving_char, "Hurt", true)
		GAME:WaitFrames(20)
		GROUND:CharSetAnim(moving_char, "None", true)
	end)
	local coro7 = TASK:BranchCoroutine(function() -- Cacnea2 is knocked back
		local moving_char = cacnea2
		GROUND:TeleportTo(moving_char, moving_char.Position.X - 48, moving_char.Position.Y + 24, Direction.Left)
		GAME:WaitFrames(10)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X + 12, moving_char.Position.Y - 6, 4, 2, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X + 12, moving_char.Position.Y - 6, 4, 1.5, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X + 12, moving_char.Position.Y - 6, 4, 1, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X + 12, moving_char.Position.Y - 6, 4, 0.5, 0)
		GROUND:CharSetAnim(moving_char, "Hurt", true)
		GAME:WaitFrames(20)
		GROUND:CharSetAnim(moving_char, "None", true)
	end)
	local coro8 = TASK:BranchCoroutine(function() -- Cacnea3 is knocked back
		local moving_char = cacnea3
		GROUND:TeleportTo(moving_char, moving_char.Position.X + 40, moving_char.Position.Y - 16, Direction.UpRight)
		GAME:WaitFrames(10)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X - 10, moving_char.Position.Y + 4, 4, 2, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X - 10, moving_char.Position.Y + 4, 4, 1.5, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X - 10, moving_char.Position.Y + 4, 4, 1, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X - 10, moving_char.Position.Y + 4, 4, 0.5, 0)
		GROUND:CharSetAnim(moving_char, "Hurt", true)
		GAME:WaitFrames(20)
		GROUND:CharSetAnim(moving_char, "None", true)
	end)
	local coro9 = TASK:BranchCoroutine(function() -- Cacnea4 is knocked back
		local moving_char = cacnea4
		GROUND:TeleportTo(moving_char, moving_char.Position.X - 40, moving_char.Position.Y - 16, Direction.UpLeft)
		GAME:WaitFrames(10)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X + 10, moving_char.Position.Y + 4, 4, 2, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X + 10, moving_char.Position.Y + 4, 4, 1.5, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X + 10, moving_char.Position.Y + 4, 4, 1, 0)
		GROUND:AnimateToPosition(moving_char, "Hurt", moving_char.Direction, moving_char.Position.X + 10, moving_char.Position.Y + 4, 4, 0.5, 0)
		GROUND:CharSetAnim(moving_char, "Hurt", true)
		GAME:WaitFrames(20)
		GROUND:CharSetAnim(moving_char, "None", true)
	end)
	local coro10 = TASK:BranchCoroutine(function() -- Fade in
		GAME:FadeIn(20)
	end)
	local coro11 = TASK:BranchCoroutine(function() -- Player characters attack and sound plays, then they turn to Cacturne
		GROUND:CharSetAnim(player, "Attack", false)
		GROUND:CharSetAnim(glaceon, "Attack", false)
		GAME:WaitFrames(5)
		SOUND:PlayBattleSE("EVT_Tackle")
		GAME:WaitFrames(50)
		GROUND:CharAnimateTurnTo(player, Direction.Up, 4)
		GAME:WaitFrames(5)
		GROUND:CharAnimateTurnTo(glaceon, Direction.Up, 4)
	end)
	TASK:JoinCoroutines({coro1,coro2,coro3,coro4,coro5, coro6,coro7,coro8,coro9, coro10,coro11})
	GAME:WaitFrames(10)
	
	UI:SetSpeaker(cacturne)
	UI:WaitShowDialogue("So,[pause=10] you've managed to flout our business rules and get away with it.")
	UI:WaitShowDialogue("...For now.")
	GAME:WaitFrames(10)
	
	GROUND:MoveToPosition(cacturne, cacturne.Position.X, cacturne.Position.Y + 24, false, 0.5)
	GAME:WaitFrames(20)
	
	UI:SetSpeaker(cacturne)
	UI:WaitShowDialogue("We know where you live,[pause=10] [color=#00FFFF]Glaceon[color].[pause=30] You and your brother both.")
	UI:WaitShowDialogue(STRINGS:Format("You won't always have {0} watching your back.", GAME:GetTeamName()))
	UI:WaitShowDialogue("And someday...[pause=0] Maybe not today,[pause=10] but someday...")
	GAME:WaitFrames(10)
	
	GROUND:MoveToPosition(cacturne, cacturne.Position.X, cacturne.Position.Y + 24, false, 0.5)
	GAME:WaitFrames(20)
	
	UI:SetSpeaker(cacturne)
	UI:SetSpeakerEmotion("Special0")
	UI:WaitShowDialogue("You're going to wish you had let us finish you off down here.")
	GAME:WaitFrames(10)
	
	SOUND:PlayBattleSE("EVT_Battle_Flash")
	GAME:FadeOut(true, 30)
	GROUND:AddMapStatus("blizzard")
	GROUND:CharSetDrawEffect(glaceon, DrawEffect.Trembling)
	GAME:WaitFrames(10)
	GAME:FadeIn(30)
	GAME:WaitFrames(10)
	
	GROUND:CharSetEmote(cacturne, "exclaim", 1)
	SOUND:PlayBattleSE("EVT_Emote_Exclaim_Surprised")
	GAME:WaitFrames(30)
	
	UI:SetSpeaker(cacturne)
	UI:SetSpeakerEmotion("Stunned")
	UI:WaitShowDialogue("W-what's she doing?!")
	GAME:WaitFrames(10)
	
	UI:SetSpeaker(glaceon)
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue("Rrrrrrrhhhhhh...!")
	GAME:WaitFrames(10)
	
	local coro1 = TASK:BranchCoroutine(function() -- Glaceon screams
		GAME:WaitFrames(25)
		UI:SetSpeaker(glaceon)
		UI:SetSpeakerEmotion("Shouting")
		UI:WaitShowTimedDialogue("[speed=0.25]RAAAAAAAAAAAAHHHHH!!!", 120)
		GAME:WaitFrames(10)
	end)
	local coro2 = TASK:BranchCoroutine(function() -- Ice particles appear from Glaceon
		GAME:WaitFrames(20)
		local anim_list = luanet.make_array(RogueEssence.Content.AnimData, {
			RogueEssence.Content.AnimData("Ice_Shard_Hit_Sparkle", 5, 0, 6, 255, Dir8.None),
			RogueEssence.Content.AnimData("Ice_Shard_Hit_Sparkle", 4, 0, 6, 255, Dir8.None),
			RogueEssence.Content.AnimData("Ice_Shard_Hit_Sparkle", 3, 0, 6, 255, Dir8.None),
			RogueEssence.Content.AnimData("Ice_Shard_Hit_Sparkle", 2, 0, 6, 255, Dir8.None),
			RogueEssence.Content.AnimData("Ice_Shard_Hit_Sparkle", 1, 0, 6, 255, Dir8.None)
		})
		
		local emitter = RogueEssence.Content.FiniteReleaseEmitter(anim_list)
		emitter.Layer = RogueEssence.Content.DrawLayer.Front
		
		emitter.Bursts = 20
		emitter.ParticlesPerBurst = 12
		emitter.BurstTime = 5
		
		emitter.StartDistance = 8
		emitter.Speed = 240
		
		GROUND:PlayVFX(emitter, glaceon.Bounds.Center.X, glaceon.Bounds.Center.Y)
		
		-- Play sound
		SOUND:PlayBattleSE("_UNK_DUN_Mist")
		SOUND:PlayBattleSE("_UNK_DUN_Shatter_2")
		GAME:WaitFrames(20)
		SOUND:PlayBattleSE("DUN_Ice_Beam")
	end)
	local coro3 = TASK:BranchCoroutine(function() -- Glaceon animates
		SOUND:PlayBattleSE("_UNK_DUN_Bright")
		animId = RogueEssence.Content.GraphicsManager.GetAnimIndex("Shoot")
		GROUND:CharSetAction(glaceon, RogueEssence.Ground.FrameGroundAction(glaceon.Position, glaceon.LocHeight, Direction.Up, animId, 0))
		GAME:WaitFrames(3)
		GROUND:CharSetAction(glaceon, RogueEssence.Ground.FrameGroundAction(glaceon.Position, glaceon.LocHeight, Direction.Up, animId, 1))
		GAME:WaitFrames(3)
		GROUND:CharSetAction(glaceon, RogueEssence.Ground.FrameGroundAction(glaceon.Position, glaceon.LocHeight, Direction.Up, animId, 2))
		GAME:WaitFrames(15)
		GROUND:CharSetAction(glaceon, RogueEssence.Ground.FrameGroundAction(glaceon.Position, glaceon.LocHeight, Direction.Up, animId, 3))
		GAME:WaitFrames(3)
		GROUND:CharSetAction(glaceon, RogueEssence.Ground.FrameGroundAction(glaceon.Position, glaceon.LocHeight, Direction.Up, animId, 4))
	end)
	local coro4 = TASK:BranchCoroutine(function() -- Screen fades out
		GAME:WaitFrames(50)
		SOUND:PlayBattleSE("EVT_CH01_Transition")
		GAME:FadeOut(true, 90)
	end)
	local coro5 = TASK:BranchCoroutine(function() -- Set character actions
		GAME:WaitFrames(22)
		GROUND:CharSetAnim(cacturne, "Hurt", true)
		GAME:WaitFrames(3)
		GROUND:CharSetAnim(player, "Hurt", true)
		GROUND:EntTurn(player, Direction.Right)
		GAME:WaitFrames(5)
		GROUND:CharSetAnim(cacnea2, "Hurt", true)
		GAME:WaitFrames(2)
		GROUND:CharSetAnim(drapion, "Hurt", true)
		GAME:WaitFrames(2)
		GROUND:CharSetAnim(cacnea3, "Hurt", true)
		GAME:WaitFrames(2)
		GROUND:CharSetAnim(cacnea4, "Hurt", true)
		GAME:WaitFrames(2)
		GROUND:CharSetAnim(tyranitar, "Hurt", true)
		GAME:WaitFrames(5)
		GROUND:CharSetAnim(cacnea1, "Hurt", true)
		GAME:WaitFrames(2)
		GROUND:CharSetAnim(excadrill, "Hurt", true)
		GAME:WaitFrames(2)
		GROUND:CharSetAnim(golem, "Hurt", true)
	end)
	TASK:JoinCoroutines({coro1,coro2,coro3,coro4,coro5})
	GAME:WaitFrames(30)
	
	-- Cacturne is now frozen
	animId = RogueEssence.Content.GraphicsManager.GetAnimIndex("Hurt")
	GROUND:CharSetAction(cacturne, RogueEssence.Ground.FrameGroundAction(cacturne.Position, cacturne.LocHeight, Direction.Down, animId, 0))
	GROUND:CharSetEmote(cacturne, "frozen", 65535)
	
	-- Snow map status ends
	GROUND:RemoveMapStatus("blizzard")
	
	-- Other Pokemon stop shivering
	GROUND:CharEndAnim(player)
	GROUND:TeleportTo(player, player.Position.X - 24, player.Position.Y)
	
	GROUND:CharEndAnim(drapion)
	GROUND:TeleportTo(drapion, drapion.Position.X - 16, drapion.Position.Y - 4)
	
	GROUND:CharEndAnim(tyranitar)
	GROUND:TeleportTo(tyranitar, tyranitar.Position.X + 16, tyranitar.Position.Y - 4)
	
	GROUND:CharEndAnim(golem)
	GROUND:TeleportTo(golem, golem.Position.X - 4, golem.Position.Y + 12)
	
	GROUND:CharEndAnim(excadrill)
	GROUND:TeleportTo(excadrill, excadrill.Position.X + 4, excadrill.Position.Y + 12)
	
	GROUND:CharEndAnim(cacnea1)
	GROUND:TeleportTo(cacnea1, cacnea1.Position.X - 24, cacnea1.Position.Y - 8)
	
	GROUND:CharEndAnim(cacnea2)
	GROUND:TeleportTo(cacnea2, cacnea2.Position.X + 24, cacnea2.Position.Y - 8)
	
	GROUND:CharEndAnim(cacnea3)
	GROUND:TeleportTo(cacnea3, cacnea3.Position.X - 24, cacnea3.Position.Y + 8)
	
	GROUND:CharEndAnim(cacnea4)
	GROUND:TeleportTo(cacnea4, cacnea4.Position.X + 24, cacnea4.Position.Y + 8)
	
	-- Glaceon stops trembling and is about to collapse
	GROUND:CharEndAnim(glaceon)
	animId = RogueEssence.Content.GraphicsManager.GetAnimIndex("Sit")
	GROUND:CharSetAction(glaceon, RogueEssence.Ground.FrameGroundAction(glaceon.Position, glaceon.LocHeight, Direction.Up, animId, 1))
	GROUND:CharEndDrawEffect(glaceon, DrawEffect.Trembling)
	
	GAME:FadeIn(60)
	GAME:WaitFrames(30)
	
	GROUND:CharTurnToCharAnimated(player, cacturne, 4)
	GAME:WaitFrames(10)
	
	GROUND:CharSetEmote(drapion, "exclaim", 1)
	SOUND:PlayBattleSE("EVT_Emote_Shock_Bad")
	GAME:WaitFrames(30)
	
	UI:SetSpeaker(drapion)
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue("T-the boss...[pause=0] He's...")
	GAME:WaitFrames(10)
	
	UI:SetSpeaker(golem)
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue("He's frozen solid!")
	GAME:WaitFrames(10)
	
	UI:SetSpeaker(excadrill)
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue("L-let's get out of here!!")
	GAME:WaitFrames(10)
	
	local coro1 = TASK:BranchCoroutine(function() -- Golem runs away
		GAME:WaitFrames(10)
		GROUND:CharAnimateTurnTo(golem, Direction.Down, 6)
		GAME:WaitFrames(6)
		GROUND:MoveToPosition(golem, golem.Position.X, golem.Position.Y + 48, false, 0.5)
		GROUND:Hide("Golem")
	end)
	local coro2 = TASK:BranchCoroutine(function() -- Excadrill runs away
		GROUND:CharAnimateTurnTo(excadrill, Direction.Down, 4)
		GAME:WaitFrames(4)
		GROUND:MoveToPosition(excadrill, excadrill.Position.X, excadrill.Position.Y + 48, false, 1.5)
		GROUND:Hide("Excadrill")
	end)
	TASK:JoinCoroutines({coro1,coro2})
	
	
	
end

return desiccated_basin_cutscene

