--[[
    init.lua
    Created: 08/06/2026 14:48:43
    Description: Autogenerated script file for the map desiccated_basin_cutscene.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local desiccated_basin_cutscene = {}

-------------------------------
-- Map Callbacks
-------------------------------
---desiccated_basin_cutscene.Init(map)
--Engine callback function
function desiccated_basin_cutscene.Init(map)


end

---desiccated_basin_cutscene.Enter(map)
--Engine callback function
function desiccated_basin_cutscene.Enter(map)

  GAME:FadeIn(20)

end

---desiccated_basin_cutscene.Exit(map)
--Engine callback function
function desiccated_basin_cutscene.Exit(map)


end

---desiccated_basin_cutscene.Update(map)
--Engine callback function
function desiccated_basin_cutscene.Update(map)


end

---desiccated_basin_cutscene.GameSave(map)
--Engine callback function
function desiccated_basin_cutscene.GameSave(map)


end

---desiccated_basin_cutscene.GameLoad(map)
--Engine callback function
function desiccated_basin_cutscene.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return desiccated_basin_cutscene

